<?php

use App\Models\Language;
use Illuminate\Database\Seeder;


class LanguagesTableSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $languages = [
            ['code'=>'ace', 'name' => 'Achinese', 'script' => 'Latn', 'native' => 'Aceh', 'regional' => ''],
            ['code'=>'af' , 'name' => 'Afrikaans',              'script' => 'Latn', 'native' => 'Afrikaans', 'regional' => 'af_ZA'],
            ['code'=>'agq', 'name' => 'Aghem', 'script' => 'Latn', 'native' => 'Aghem', 'regional' => ''],
            ['code'=>'ak' , 'name' => 'Akan', 'script' => 'Latn', 'native' => 'Akan', 'regional' => 'ak_GH'],
            ['code'=>'an' , 'name' => 'Aragonese',              'script' => 'Latn', 'native' => 'aragonés', 'regional' => 'an_ES'],
            ['code'=>'cch', 'name' => 'Atsam', 'script' => 'Latn', 'native' => 'Atsam', 'regional' => ''],
            ['code'=>'gn' , 'name' => 'Guaraní', 'script' => 'Latn', 'native' => 'Avañe’ẽ', 'regional' => ''],
            ['code'=>'ae' , 'name' => 'Avestan', 'script' => 'Latn', 'native' => 'avesta', 'regional' => ''],
            ['code'=>'ay' , 'name' => 'Aymara', 'script' => 'Latn', 'native' => 'aymar aru', 'regional' => 'ay_PE'],
            ['code'=>'az' , 'name' => 'Azerbaijani (Latin)',    'script' => 'Latn', 'native' => 'azərbaycanca', 'regional' => 'az_AZ'],
            ['code'=>'id' , 'name' => 'Indonesian',             'script' => 'Latn', 'native' => 'Bahasa Indonesia', 'regional' => 'id_ID'],
            ['code'=>'ms' , 'name' => 'Malay', 'script' => 'Latn', 'native' => 'Bahasa Melayu', 'regional' => 'ms_MY'],
            ['code'=>'bm' , 'name' => 'Bambara', 'script' => 'Latn', 'native' => 'bamanakan', 'regional' => ''],
            ['code'=>'jv' , 'name' => 'Javanese (Latin)',       'script' => 'Latn', 'native' => 'Basa Jawa', 'regional' => ''],
            ['code'=>'su' , 'name' => 'Sundanese',              'script' => 'Latn', 'native' => 'Basa Sunda', 'regional' => ''],
            ['code'=>'bh' , 'name' => 'Bihari', 'script' => 'Latn', 'native' => 'Bihari', 'regional' => ''],
            ['code'=>'bi' , 'name' => 'Bislama', 'script' => 'Latn', 'native' => 'Bislama', 'regional' => ''],
            ['code'=>'nb' , 'name' => 'Norwegian Bokmål',       'script' => 'Latn', 'native' => 'Bokmål', 'regional' => 'nb_NO'],
            ['code'=>'bs' , 'name' => 'Bosnian', 'script' => 'Latn', 'native' => 'bosanski', 'regional' => 'bs_BA'],
            ['code'=>'br' , 'name' => 'Breton', 'script' => 'Latn', 'native' => 'brezhoneg', 'regional' => 'br_FR'],
            ['code'=>'ca' , 'name' => 'Catalan', 'script' => 'Latn', 'native' => 'català', 'regional' => 'ca_ES'],
            ['code'=>'ch' , 'name' => 'Chamorro', 'script' => 'Latn', 'native' => 'Chamoru', 'regional' => ''],
            ['code'=>'ny' , 'name' => 'Chewa', 'script' => 'Latn', 'native' => 'chiCheŵa', 'regional' => ''],
            ['code'=>'kde', 'name' => 'Makonde', 'script' => 'Latn', 'native' => 'Chimakonde', 'regional' => ''],
            ['code'=>'sn' , 'name' => 'Shona', 'script' => 'Latn', 'native' => 'chiShona', 'regional' => ''],
            ['code'=>'co' , 'name' => 'Corsican', 'script' => 'Latn', 'native' => 'corsu', 'regional' => ''],
            ['code'=>'cy' , 'name' => 'Welsh', 'script' => 'Latn', 'native' => 'Cymraeg', 'regional' => 'cy_GB'],
            ['code'=>'da' , 'name' => 'Danish', 'script' => 'Latn', 'native' => 'dansk', 'regional' => 'da_DK'],
            ['code'=>'se' , 'name' => 'Northern Sami',          'script' => 'Latn', 'native' => 'davvisámegiella', 'regional' => 'se_NO'],
            ['code'=>'de' , 'name' => 'German', 'script' => 'Latn', 'native' => 'Deutsch', 'regional' => 'de_DE'],
            ['code'=>'luo', 'name' => 'Luo', 'script' => 'Latn', 'native' => 'Dholuo', 'regional' => ''],
            ['code'=>'nv' , 'name' => 'Navajo', 'script' => 'Latn', 'native' => 'Diné bizaad', 'regional' => ''],
            ['code'=>'dua', 'name' => 'Duala', 'script' => 'Latn', 'native' => 'duálá', 'regional' => ''],
            ['code'=>'et' , 'name' => 'Estonian', 'script' => 'Latn', 'native' => 'eesti', 'regional' => 'et_EE'],
            ['code'=>'na' , 'name' => 'Nauru', 'script' => 'Latn', 'native' => 'Ekakairũ Naoero', 'regional' => ''],
            ['code'=>'guz', 'name' => 'Ekegusii', 'script' => 'Latn', 'native' => 'Ekegusii', 'regional' => ''],
            ['code'=>'en' , 'name' => 'English', 'script' => 'Latn', 'native' => 'EN', 'regional' => 'en_GB'],
 			['code'=>'en-AU','name' => 'Australian English',     'script' => 'Latn', 'native' => 'Australian English', 'regional' => 'en_AU'],
 			['code'=>'en-GB','name' => 'British English',        'script' => 'Latn', 'native' => 'British English', 'regional' => 'en_GB'],
 			['code'=>'en-US','name' => 'U.S. English',           'script' => 'Latn', 'native' => 'U.S. English', 'regional' => 'en_US'],
            ['code'=>'es' , 'name' => 'Spanish', 'script' => 'Latn', 'native' => 'español', 'regional' => 'es_ES'],
            ['code'=>'eo' , 'name' => 'Esperanto',              'script' => 'Latn', 'native' => 'esperanto', 'regional' => ''],
            ['code'=>'eu' , 'name' => 'Basque', 'script' => 'Latn', 'native' => 'euskara', 'regional' => 'eu_ES'],
            ['code'=>'ewo', 'name' => 'Ewondo', 'script' => 'Latn', 'native' => 'ewondo', 'regional' => ''],
            ['code'=>'ee' , 'name' => 'Ewe', 'script' => 'Latn', 'native' => 'eʋegbe', 'regional' => ''],
            ['code'=>'fil', 'name' => 'Filipino', 'script' => 'Latn', 'native' => 'Filipino', 'regional' => 'fil_PH'],
            ['code'=>'fr' , 'name' => 'French', 'script' => 'Latn', 'native' => 'français', 'regional' => 'fr_FR'],
 			['code'=>'fr-CA','name' => 'Canadian French',        'script' => 'Latn', 'native' => 'français canadien', 'regional' => 'fr_CA'],
            ['code'=>'fy' , 'name' => 'Western Frisian',        'script' => 'Latn', 'native' => 'frysk', 'regional' => 'fy_DE'],
            ['code'=>'fur', 'name' => 'Friulian', 'script' => 'Latn', 'native' => 'furlan', 'regional' => 'fur_IT'],
            ['code'=>'fo' , 'name' => 'Faroese', 'script' => 'Latn', 'native' => 'føroyskt', 'regional' => 'fo_FO'],
            ['code'=>'gaa', 'name' => 'Ga', 'script' => 'Latn', 'native' => 'Ga', 'regional' => ''],
            ['code'=>'ga' , 'name' => 'Irish', 'script' => 'Latn', 'native' => 'Gaeilge', 'regional' => 'ga_IE'],
            ['code'=>'gv' , 'name' => 'Manx', 'script' => 'Latn', 'native' => 'Gaelg', 'regional' => 'gv_GB'],
            ['code'=>'sm' , 'name' => 'Samoan', 'script' => 'Latn', 'native' => 'Gagana fa’a Sāmoa', 'regional' => ''],
            ['code'=>'gl' , 'name' => 'Galician', 'script' => 'Latn', 'native' => 'galego', 'regional' => 'gl_ES'],
            ['code'=>'ki' , 'name' => 'Kikuyu', 'script' => 'Latn', 'native' => 'Gikuyu', 'regional' => ''],
            ['code'=>'gd' , 'name' => 'Scottish Gaelic',        'script' => 'Latn', 'native' => 'Gàidhlig', 'regional' => 'gd_GB'],
            ['code'=>'ha' , 'name' => 'Hausa', 'script' => 'Latn', 'native' => 'Hausa', 'regional' => 'ha_NG'],
            ['code'=>'bez', 'name' => 'Bena', 'script' => 'Latn', 'native' => 'Hibena', 'regional' => ''],
            ['code'=>'ho' , 'name' => 'Hiri Motu',              'script' => 'Latn', 'native' => 'Hiri Motu', 'regional' => ''],
            ['code'=>'hr' , 'name' => 'Croatian', 'script' => 'Latn', 'native' => 'hrvatski', 'regional' => 'hr_HR'],
            ['code'=>'bem', 'name' => 'Bemba', 'script' => 'Latn', 'native' => 'Ichibemba', 'regional' => 'bem_ZM'],
            ['code'=>'io' , 'name' => 'Ido', 'script' => 'Latn', 'native' => 'Ido', 'regional' => ''],
            ['code'=>'ig' , 'name' => 'Igbo', 'script' => 'Latn', 'native' => 'Igbo', 'regional' => 'ig_NG'],
            ['code'=>'rn' , 'name' => 'Rundi', 'script' => 'Latn', 'native' => 'Ikirundi', 'regional' => ''],
            ['code'=>'ia' , 'name' => 'Interlingua',            'script' => 'Latn', 'native' => 'interlingua', 'regional' => 'ia_FR'],
 			['code'=> 'iu-Latn', 'name' => 'Inuktitut (Latin)',      'script' => 'Latn', 'native' => 'Inuktitut', 'regional' => 'iu_CA'],
            ['code'=>'sbp', 'name' => 'Sileibi', 'script' => 'Latn', 'native' => 'Ishisangu', 'regional' => ''],
            ['code'=>'nd' , 'name' => 'North Ndebele',          'script' => 'Latn', 'native' => 'isiNdebele', 'regional' => ''],
            ['code'=>'nr' , 'name' => 'South Ndebele',          'script' => 'Latn', 'native' => 'isiNdebele', 'regional' => 'nr_ZA'],
            ['code'=>'xh' , 'name' => 'Xhosa', 'script' => 'Latn', 'native' => 'isiXhosa', 'regional' => 'xh_ZA'],
            ['code'=>'zu' , 'name' => 'Zulu', 'script' => 'Latn', 'native' => 'isiZulu', 'regional' => 'zu_ZA'],
            ['code'=>'it' , 'name' => 'Italian', 'script' => 'Latn', 'native' => 'italiano', 'regional' => 'it_IT'],
            ['code'=>'ik' , 'name' => 'Inupiaq', 'script' => 'Latn', 'native' => 'Iñupiaq', 'regional' => 'ik_CA'],
            ['code'=>'dyo', 'name' => 'Jola-Fonyi',             'script' => 'Latn', 'native' => 'joola', 'regional' => ''],
            ['code'=>'kea', 'name' => 'Kabuverdianu',           'script' => 'Latn', 'native' => 'kabuverdianu', 'regional' => ''],
            ['code'=>'kaj', 'name' => 'Jju', 'script' => 'Latn', 'native' => 'Kaje', 'regional' => ''],
            ['code'=>'mh' , 'name' => 'Marshallese',            'script' => 'Latn', 'native' => 'Kajin M̧ajeļ', 'regional' => 'mh_MH'],
            ['code'=>'kl' , 'name' => 'Kalaallisut',            'script' => 'Latn', 'native' => 'kalaallisut', 'regional' => 'kl_GL'],
            ['code'=>'kln', 'name' => 'Kalenjin', 'script' => 'Latn', 'native' => 'Kalenjin', 'regional' => ''],
            ['code'=>'kr' , 'name' => 'Kanuri', 'script' => 'Latn', 'native' => 'Kanuri', 'regional' => ''],
            ['code'=>'kcg', 'name' => 'Tyap', 'script' => 'Latn', 'native' => 'Katab', 'regional' => ''],
            ['code'=>'kw' , 'name' => 'Cornish', 'script' => 'Latn', 'native' => 'kernewek', 'regional' => 'kw_GB'],
            ['code'=>'naq', 'name' => 'Nama', 'script' => 'Latn', 'native' => 'Khoekhoegowab', 'regional' => ''],
            ['code'=>'rof', 'name' => 'Rombo', 'script' => 'Latn', 'native' => 'Kihorombo', 'regional' => ''],
            ['code'=>'kam', 'name' => 'Kamba', 'script' => 'Latn', 'native' => 'Kikamba', 'regional' => ''],
            ['code'=>'kg' , 'name' => 'Kongo', 'script' => 'Latn', 'native' => 'Kikongo', 'regional' => ''],
            ['code'=>'jmc', 'name' => 'Machame', 'script' => 'Latn', 'native' => 'Kimachame', 'regional' => ''],
            ['code'=>'rw' , 'name' => 'Kinyarwanda',            'script' => 'Latn', 'native' => 'Kinyarwanda', 'regional' => 'rw_RW'],
            ['code'=>'asa', 'name' => 'Kipare', 'script' => 'Latn', 'native' => 'Kipare', 'regional' => ''],
            ['code'=>'rwk', 'name' => 'Rwa', 'script' => 'Latn', 'native' => 'Kiruwa', 'regional' => ''],
            ['code'=>'saq', 'name' => 'Samburu', 'script' => 'Latn', 'native' => 'Kisampur', 'regional' => ''],
            ['code'=>'ksb', 'name' => 'Shambala', 'script' => 'Latn', 'native' => 'Kishambaa', 'regional' => ''],
            ['code'=>'swc', 'name' => 'Congo Swahili',          'script' => 'Latn', 'native' => 'Kiswahili ya Kongo', 'regional' => ''],
            ['code'=>'sw' , 'name' => 'Swahili', 'script' => 'Latn', 'native' => 'Kiswahili', 'regional' => 'sw_KE'],
            ['code'=>'dav', 'name' => 'Dawida', 'script' => 'Latn', 'native' => 'Kitaita', 'regional' => ''],
            ['code'=>'teo', 'name' => 'Teso', 'script' => 'Latn', 'native' => 'Kiteso', 'regional' => ''],
            ['code'=>'khq', 'name' => 'Koyra Chiini',           'script' => 'Latn', 'native' => 'Koyra ciini', 'regional' => ''],
            ['code'=>'ses', 'name' => 'Songhay', 'script' => 'Latn', 'native' => 'Koyraboro senni', 'regional' => ''],
            ['code'=>'mfe', 'name' => 'Morisyen', 'script' => 'Latn', 'native' => 'kreol morisien', 'regional' => ''],
            ['code'=>'ht' , 'name' => 'Haitian', 'script' => 'Latn', 'native' => 'Kreyòl ayisyen', 'regional' => 'ht_HT'],
            ['code'=>'kj' , 'name' => 'Kuanyama', 'script' => 'Latn', 'native' => 'Kwanyama', 'regional' => ''],
            ['code'=>'ksh', 'name' => 'Kölsch', 'script' => 'Latn', 'native' => 'Kölsch', 'regional' => ''],
            ['code'=>'ebu', 'name' => 'Kiembu', 'script' => 'Latn', 'native' => 'Kĩembu', 'regional' => ''],
            ['code'=>'mer', 'name' => 'Kimîîru', 'script' => 'Latn', 'native' => 'Kĩmĩrũ', 'regional' => ''],
            ['code'=>'lag', 'name' => 'Langi', 'script' => 'Latn', 'native' => 'Kɨlaangi', 'regional' => ''],
            ['code'=>'lah', 'name' => 'Lahnda', 'script' => 'Latn', 'native' => 'Lahnda', 'regional' => ''],
            ['code'=>'la' , 'name' => 'Latin', 'script' => 'Latn', 'native' => 'latine', 'regional' => ''],
            ['code'=>'lv' , 'name' => 'Latvian', 'script' => 'Latn', 'native' => 'latviešu', 'regional' => 'lv_LV'],
            ['code'=>'to' , 'name' => 'Tongan', 'script' => 'Latn', 'native' => 'lea fakatonga', 'regional' => ''],
            ['code'=>'lt' , 'name' => 'Lithuanian',             'script' => 'Latn', 'native' => 'lietuvių', 'regional' => 'lt_LT'],
            ['code'=>'li' , 'name' => 'Limburgish',             'script' => 'Latn', 'native' => 'Limburgs', 'regional' => 'li_BE'],
            ['code'=>'ln' , 'name' => 'Lingala', 'script' => 'Latn', 'native' => 'lingála', 'regional' => ''],
            ['code'=>'lg' , 'name' => 'Ganda', 'script' => 'Latn', 'native' => 'Luganda', 'regional' => 'lg_UG'],
            ['code'=>'luy', 'name' => 'Oluluyia', 'script' => 'Latn', 'native' => 'Luluhia', 'regional' => ''],
            ['code'=>'lb' , 'name' => 'Luxembourgish',          'script' => 'Latn', 'native' => 'Lëtzebuergesch', 'regional' => 'lb_LU'],
            ['code'=>'hu' , 'name' => 'Hungarian',              'script' => 'Latn', 'native' => 'magyar', 'regional' => 'hu_HU'],
            ['code'=>'mgh', 'name' => 'Makhuwa-Meetto',         'script' => 'Latn', 'native' => 'Makua', 'regional' => ''],
            ['code'=>'mg' , 'name' => 'Malagasy', 'script' => 'Latn', 'native' => 'Malagasy', 'regional' => 'mg_MG'],
            ['code'=>'mt' , 'name' => 'Maltese', 'script' => 'Latn', 'native' => 'Malti', 'regional' => 'mt_MT'],
            ['code'=>'mtr', 'name' => 'Mewari', 'script' => 'Latn', 'native' => 'Mewari', 'regional' => ''],
            ['code'=>'mua', 'name' => 'Mundang', 'script' => 'Latn', 'native' => 'Mundang', 'regional' => ''],
            ['code'=>'mi' , 'name' => 'Māori', 'script' => 'Latn', 'native' => 'Māori', 'regional' => 'mi_NZ'],
            ['code'=>'nl' , 'name' => 'Dutch', 'script' => 'Latn', 'native' => 'Nederlands', 'regional' => 'nl_NL'],
            ['code'=>'nmg', 'name' => 'Kwasio', 'script' => 'Latn', 'native' => 'ngumba', 'regional' => ''],
            ['code'=>'yav', 'name' => 'Yangben', 'script' => 'Latn', 'native' => 'nuasue', 'regional' => ''],
            ['code'=>'nn' , 'name' => 'Norwegian Nynorsk',      'script' => 'Latn', 'native' => 'nynorsk', 'regional' => 'nn_NO'],
            ['code'=>'oc' , 'name' => 'Occitan', 'script' => 'Latn', 'native' => 'occitan', 'regional' => 'oc_FR'],
            ['code'=>'ang', 'name' => 'Old English',            'script' => 'Runr', 'native' => 'Old English', 'regional' => ''],
            ['code'=>'xog', 'name' => 'Soga', 'script' => 'Latn', 'native' => 'Olusoga', 'regional' => ''],
            ['code'=>'om' , 'name' => 'Oromo', 'script' => 'Latn', 'native' => 'Oromoo', 'regional' => 'om_ET'],
            ['code'=>'ng' , 'name' => 'Ndonga', 'script' => 'Latn', 'native' => 'OshiNdonga', 'regional' => ''],
            ['code'=>'hz' , 'name' => 'Herero', 'script' => 'Latn', 'native' => 'Otjiherero', 'regional' => ''],
 			['code' => 'uz-Latn', 'name' => 'Uzbek (Latin)',          'script' => 'Latn', 'native' => 'oʼzbekcha', 'regional' => 'uz_UZ'],
            ['code'=>'nds', 'name' => 'Low German',             'script' => 'Latn', 'native' => 'Plattdüütsch', 'regional' => 'nds_DE'],
            ['code'=>'pl' , 'name' => 'Polish', 'script' => 'Latn', 'native' => 'polski', 'regional' => 'pl_PL'],
            ['code'=>'pt' , 'name' => 'Portuguese',             'script' => 'Latn', 'native' => 'português', 'regional' => 'pt_PT'],
 			['code' => 'pt-BR', 'name' => 'Brazilian Portuguese',   'script' => 'Latn', 'native' => 'português do Brasil', 'regional' => 'pt_BR'],
            ['code'=>'ff' , 'name' => 'Fulah', 'script' => 'Latn', 'native' => 'Pulaar', 'regional' => 'ff_SN'],
            ['code'=>'pi' , 'name' => 'Pahari-Potwari',         'script' => 'Latn', 'native' => 'Pāli', 'regional' => ''],
            ['code'=>'aa' , 'name' => 'Afar', 'script' => 'Latn', 'native' => 'Qafar', 'regional' => 'aa_ER'],
            ['code'=>'ty' , 'name' => 'Tahitian', 'script' => 'Latn', 'native' => 'Reo Māohi', 'regional' => ''],
            ['code'=>'ksf', 'name' => 'Bafia', 'script' => 'Latn', 'native' => 'rikpa', 'regional' => ''],
            ['code'=>'ro' , 'name' => 'Romanian', 'script' => 'Latn', 'native' => 'română', 'regional' => 'ro_RO'],
            ['code'=>'cgg', 'name' => 'Chiga', 'script' => 'Latn', 'native' => 'Rukiga', 'regional' => ''],
            ['code'=>'rm' , 'name' => 'Romansh', 'script' => 'Latn', 'native' => 'rumantsch', 'regional' => ''],
            ['code'=>'qu' , 'name' => 'Quechua', 'script' => 'Latn', 'native' => 'Runa Simi', 'regional' => ''],
            ['code'=>'nyn', 'name' => 'Nyankole', 'script' => 'Latn', 'native' => 'Runyankore', 'regional' => ''],
            ['code'=>'ssy', 'name' => 'Saho', 'script' => 'Latn', 'native' => 'Saho', 'regional' => ''],
            ['code'=>'sc' , 'name' => 'Sardinian',              'script' => 'Latn', 'native' => 'sardu', 'regional' => 'sc_IT'],
 			['code' => 'de-CH', 'name' => 'Swiss High German',      'script' => 'Latn', 'native' => 'Schweizer Hochdeutsch', 'regional' => 'de_CH'],
            ['code'=>'gsw', 'name' => 'Swiss German',           'script' => 'Latn', 'native' => 'Schwiizertüütsch', 'regional' => ''],
            ['code'=>'trv', 'name' => 'Taroko', 'script' => 'Latn', 'native' => 'Seediq', 'regional' => ''],
            ['code'=>'seh', 'name' => 'Sena', 'script' => 'Latn', 'native' => 'sena', 'regional' => ''],
            ['code'=>'nso', 'name' => 'Northern Sotho',         'script' => 'Latn', 'native' => 'Sesotho sa Leboa', 'regional' => 'nso_ZA'],
            ['code'=>'st' , 'name' => 'Southern Sotho',         'script' => 'Latn', 'native' => 'Sesotho', 'regional' => 'st_ZA'],
            ['code'=>'tn' , 'name' => 'Tswana', 'script' => 'Latn', 'native' => 'Setswana', 'regional' => 'tn_ZA'],
            ['code'=>'sq' , 'name' => 'Albanian', 'script' => 'Latn', 'native' => 'shqip', 'regional' => 'sq_AL'],
            ['code'=>'sid', 'name' => 'Sidamo', 'script' => 'Latn', 'native' => 'Sidaamu Afo', 'regional' => 'sid_ET'],
            ['code'=>'ss' , 'name' => 'Swati', 'script' => 'Latn', 'native' => 'Siswati', 'regional' => 'ss_ZA'],
            ['code'=>'sk' , 'name' => 'Slovak', 'script' => 'Latn', 'native' => 'slovenčina', 'regional' => 'sk_SK'],
            ['code'=>'sl' , 'name' => 'Slovene', 'script' => 'Latn', 'native' => 'slovenščina', 'regional' => 'sl_SI'],
            ['code'=>'so' , 'name' => 'Somali', 'script' => 'Latn', 'native' => 'Soomaali', 'regional' => 'so_SO'],
 			['code' => 'sr-Latn', 'name' => 'Serbian (Latin)',        'script' => 'Latn', 'native' => 'Srpski', 'regional' => 'sr_RS'],
            ['code'=>'sh' , 'name' => 'Serbo-Croatian',         'script' => 'Latn', 'native' => 'srpskohrvatski', 'regional' => ''],
            ['code'=>'fi' , 'name' => 'Finnish', 'script' => 'Latn', 'native' => 'suomi', 'regional' => 'fi_FI'],
            ['code'=>'sv' , 'name' => 'Swedish', 'script' => 'Latn', 'native' => 'svenska', 'regional' => 'sv_SE'],
            ['code'=>'sg' , 'name' => 'Sango', 'script' => 'Latn', 'native' => 'Sängö', 'regional' => ''],
            ['code'=>'tl' , 'name' => 'Tagalog', 'script' => 'Latn', 'native' => 'Tagalog', 'regional' => 'tl_PH'],
 			['code' => 'tzm-Latn', 'name' => 'Central Atlas Tamazight (Latin)', 'script' => 'Latn', 'native' => 'Tamazight', 'regional' => ''],
            ['code'=>'kab', 'name' => 'Kabyle', 'script' => 'Latn', 'native' => 'Taqbaylit', 'regional' => 'kab_DZ'],
            ['code'=>'twq', 'name' => 'Tasawaq', 'script' => 'Latn', 'native' => 'Tasawaq senni', 'regional' => ''],
            ['code'=>'shi', 'name' => 'Tachelhit (Latin)',      'script' => 'Latn', 'native' => 'Tashelhit', 'regional' => ''],
            ['code'=>'nus', 'name' => 'Nuer', 'script' => 'Latn', 'native' => 'Thok Nath', 'regional' => ''],
            ['code'=>'vi' , 'name' => 'Vietnamese',             'script' => 'Latn', 'native' => 'Tiếng Việt', 'regional' => 'vi_VN'],
 			['code' => 'tg-Latn', 'name' => 'Tajik (Latin)',          'script' => 'Latn', 'native' => 'tojikī', 'regional' => 'tg_TJ'],
            ['code'=>'lu' , 'name' => 'Luba-Katanga',           'script' => 'Latn', 'native' => 'Tshiluba', 'regional' => 've_ZA'],
            ['code'=>'ve' , 'name' => 'Venda', 'script' => 'Latn', 'native' => 'Tshivenḓa', 'regional' => ''],
            ['code'=>'tw' , 'name' => 'Twi', 'script' => 'Latn', 'native' => 'Twi', 'regional' => ''],
            ['code'=>'tr' , 'name' => 'Turkish', 'script' => 'Latn', 'native' => 'Türkçe', 'regional' => 'tr_TR'],
            ['code'=>'ale', 'name' => 'Aleut', 'script' => 'Latn', 'native' => 'Unangax tunuu', 'regional' => ''],
 			['code' => 'ca-valencia', 'name' => 'Valencian',              'script' => 'Latn', 'native' => 'valencià', 'regional' => ''],
 			['code' => 'vai-Latn', 'name' => 'Vai (Latin)',            'script' => 'Latn', 'native' => 'Viyamíĩ', 'regional' => ''],
            ['code'=>'vo' , 'name' => 'Volapük', 'script' => 'Latn', 'native' => 'Volapük', 'regional' => ''],
            ['code'=>'fj' , 'name' => 'Fijian', 'script' => 'Latn', 'native' => 'vosa Vakaviti', 'regional' => ''],
            ['code'=>'wa' , 'name' => 'Walloon', 'script' => 'Latn', 'native' => 'Walon', 'regional' => 'wa_BE'],
            ['code'=>'wae', 'name' => 'Walser', 'script' => 'Latn', 'native' => 'Walser', 'regional' => 'wae_CH'],
            ['code'=>'wen', 'name' => 'Sorbian', 'script' => 'Latn', 'native' => 'Wendic', 'regional' => ''],
            ['code'=>'wo' , 'name' => 'Wolof', 'script' => 'Latn', 'native' => 'Wolof', 'regional' => 'wo_SN'],
            ['code'=>'ts' , 'name' => 'Tsonga', 'script' => 'Latn', 'native' => 'Xitsonga', 'regional' => 'ts_ZA'],
            ['code'=>'dje', 'name' => 'Zarma', 'script' => 'Latn', 'native' => 'Zarmaciine', 'regional' => ''],
            ['code'=>'yo' , 'name' => 'Yoruba', 'script' => 'Latn', 'native' => 'Èdè Yorùbá', 'regional' => 'yo_NG'],
 			['code' => 'de-AT', 'name' => 'Austrian German',        'script' => 'Latn', 'native' => 'Österreichisches Deutsch', 'regional' => 'de_AT'],
            ['code'=>'is' , 'name' => 'Icelandic',              'script' => 'Latn', 'native' => 'íslenska', 'regional' => 'is_IS'],
            ['code'=>'cs' , 'name' => 'Czech', 'script' => 'Latn', 'native' => 'čeština', 'regional' => 'cs_CZ'],
            ['code'=>'bas', 'name' => 'Basa', 'script' => 'Latn', 'native' => 'Ɓàsàa', 'regional' => ''],
            ['code'=>'mas', 'name' => 'Masai', 'script' => 'Latn', 'native' => 'ɔl-Maa', 'regional' => ''],
            ['code'=>'haw', 'name' => 'Hawaiian', 'script' => 'Latn', 'native' => 'ʻŌlelo Hawaiʻi', 'regional' => ''],
            ['code'=>'el' , 'name' => 'Greek', 'script' => 'Grek', 'native' => 'Ελληνικά', 'regional' => 'el_GR'],
            ['code'=>'uz' , 'name' => 'Uzbek (Cyrillic)',       'script' => 'Cyrl', 'native' => 'Ўзбек', 'regional' => 'uz_UZ'],
 			['code' => 'az-Cyrl', 'name' => 'Azerbaijani (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Азәрбајҹан', 'regional' => 'uz_UZ'],
            ['code'=>'ab' , 'name' => 'Abkhazian',              'script' => 'Cyrl', 'native' => 'Аҧсуа', 'regional' => ''],
            ['code'=>'os' , 'name' => 'Ossetic', 'script' => 'Cyrl', 'native' => 'Ирон', 'regional' => 'os_RU'],
            ['code'=>'ky' , 'name' => 'Kyrgyz', 'script' => 'Cyrl', 'native' => 'Кыргыз', 'regional' => 'ky_KG'],
            ['code'=>'sr' , 'name' => 'Serbian (Cyrillic)',     'script' => 'Cyrl', 'native' => 'Српски', 'regional' => 'sr_RS'],
            ['code'=>'av' , 'name' => 'Avaric', 'script' => 'Cyrl', 'native' => 'авар мацӀ', 'regional' => ''],
            ['code'=>'ady', 'name' => 'Adyghe', 'script' => 'Cyrl', 'native' => 'адыгэбзэ', 'regional' => ''],
            ['code'=>'ba' , 'name' => 'Bashkir', 'script' => 'Cyrl', 'native' => 'башҡорт теле', 'regional' => ''],
            ['code'=>'be' , 'name' => 'Belarusian',             'script' => 'Cyrl', 'native' => 'беларуская', 'regional' => 'be_BY'],
            ['code'=>'bg' , 'name' => 'Bulgarian',              'script' => 'Cyrl', 'native' => 'български', 'regional' => 'bg_BG'],
            ['code'=>'kv' , 'name' => 'Komi', 'script' => 'Cyrl', 'native' => 'коми кыв', 'regional' => ''],
            ['code'=>'mk' , 'name' => 'Macedonian',             'script' => 'Cyrl', 'native' => 'MK', 'regional' => 'mk_MK'],
            ['code'=>'mn' , 'name' => 'Mongolian (Cyrillic)',   'script' => 'Cyrl', 'native' => 'монгол', 'regional' => 'mn_MN'],
            ['code'=>'ce' , 'name' => 'Chechen', 'script' => 'Cyrl', 'native' => 'нохчийн мотт', 'regional' => 'ce_RU'],
            ['code'=>'ru' , 'name' => 'Russian', 'script' => 'Cyrl', 'native' => 'русский', 'regional' => 'ru_RU'],
            ['code'=>'sah', 'name' => 'Yakut', 'script' => 'Cyrl', 'native' => 'саха тыла', 'regional' => ''],
            ['code'=>'tt' , 'name' => 'Tatar', 'script' => 'Cyrl', 'native' => 'татар теле', 'regional' => 'tt_RU'],
            ['code'=>'tg' , 'name' => 'Tajik (Cyrillic)',       'script' => 'Cyrl', 'native' => 'тоҷикӣ', 'regional' => 'tg_TJ'],
            ['code'=>'tk' , 'name' => 'Turkmen', 'script' => 'Cyrl', 'native' => 'түркменче', 'regional' => 'tk_TM'],
            ['code'=>'uk' , 'name' => 'Ukrainian',              'script' => 'Cyrl', 'native' => 'українська', 'regional' => 'uk_UA'],
            ['code'=>'cv' , 'name' => 'Chuvash', 'script' => 'Cyrl', 'native' => 'чӑваш чӗлхи', 'regional' => 'cv_RU'],
            ['code'=>'cu' , 'name' => 'Church Slavic',          'script' => 'Cyrl', 'native' => 'ѩзыкъ словѣньскъ', 'regional' => ''],
            ['code'=>'kk' , 'name' => 'Kazakh', 'script' => 'Cyrl', 'native' => 'қазақ тілі', 'regional' => 'kk_KZ'],
            ['code'=>'hy' , 'name' => 'Armenian', 'script' => 'Armn', 'native' => 'Հայերեն', 'regional' => 'hy_AM'],
            ['code'=>'yi' , 'name' => 'Yiddish', 'script' => 'Hebr', 'native' => 'ייִדיש', 'regional' => 'yi_US'],
            ['code'=>'he' , 'name' => 'Hebrew', 'script' => 'Hebr', 'native' => 'עברית', 'regional' => 'he_IL'],
            ['code'=>'ug' , 'name' => 'Uyghur', 'script' => 'Arab', 'native' => 'ئۇيغۇرچە', 'regional' => 'ug_CN'],
            ['code'=>'ur' , 'name' => 'Urdu', 'script' => 'Arab', 'native' => 'اردو', 'regional' => 'ur_PK'],
            ['code'=>'ar' , 'name' => 'Arabic', 'script' => 'Arab', 'native' => 'العربية', 'regional' => 'ar_AE'],
 			['code' => 'uz-Arab', 'name' => 'Uzbek (Arabic)',         'script' => 'Arab', 'native' => 'اۉزبېک', 'regional' => ''],
 			['code' => 'tg-Arab', 'name' => 'Tajik (Arabic)',         'script' => 'Arab', 'native' => 'تاجیکی', 'regional' => 'tg_TJ'],
            ['code'=>'sd' , 'name' => 'Sindhi', 'script' => 'Arab', 'native' => 'سنڌي', 'regional' => 'sd_IN'],
            ['code'=>'fa' , 'name' => 'Persian', 'script' => 'Arab', 'native' => 'فارسی', 'regional' => 'fa_IR'],
 			['code' => 'pa-Arab', 'name' => 'Punjabi (Arabic)',       'script' => 'Arab', 'native' => 'پنجاب', 'regional' => 'pa_IN'],
            ['code'=>'ps' , 'name' => 'Pashto', 'script' => 'Arab', 'native' => 'پښتو', 'regional' => 'ps_AF'],
            ['code'=>'ks' , 'name' => 'Kashmiri (Arabic)',      'script' => 'Arab', 'native' => 'کأشُر', 'regional' => 'ks_IN'],
            ['code'=>'ku' , 'name' => 'Kurdish', 'script' => 'Arab', 'native' => 'کوردی', 'regional' => 'ku_TR'],
            ['code'=>'dv' , 'name' => 'Divehi', 'script' => 'Thaa', 'native' => 'ދިވެހިބަސް', 'regional' => 'dv_MV'],
 			['code'=>'ks-Deva', 'name' => 'Kashmiri (Devaganari)',  'script' => 'Deva', 'native' => 'कॉशुर', 'regional' => 'ks_IN'],
            ['code'=>'kok', 'name' => 'Konkani', 'script' => 'Deva', 'native' => 'कोंकणी', 'regional' => 'kok_IN'],
            ['code'=>'doi', 'name' => 'Dogri', 'script' => 'Deva', 'native' => 'डोगरी', 'regional' => 'doi_IN'],
            ['code'=>'ne' , 'name' => 'Nepali', 'script' => 'Deva', 'native' => 'नेपाली', 'regional' => ''],
            ['code'=>'pra', 'name' => 'Prakrit', 'script' => 'Deva', 'native' => 'प्राकृत', 'regional' => ''],
            ['code'=>'brx', 'name' => 'Bodo', 'script' => 'Deva', 'native' => 'बड़ो', 'regional' => 'brx_IN'],
            ['code'=>'bra', 'name' => 'Braj', 'script' => 'Deva', 'native' => 'ब्रज भाषा', 'regional' => ''],
            ['code'=>'mr' , 'name' => 'Marathi', 'script' => 'Deva', 'native' => 'मराठी', 'regional' => 'mr_IN'],
            ['code'=>'mai', 'name' => 'Maithili', 'script' => 'Tirh', 'native' => 'मैथिली', 'regional' => 'mai_IN'],
            ['code'=>'raj', 'name' => 'Rajasthani',             'script' => 'Deva', 'native' => 'राजस्थानी', 'regional' => ''],
            ['code'=>'sa' , 'name' => 'Sanskrit', 'script' => 'Deva', 'native' => 'संस्कृतम्', 'regional' => 'sa_IN'],
            ['code'=>'hi' , 'name' => 'Hindi', 'script' => 'Deva', 'native' => 'हिन्दी', 'regional' => 'hi_IN'],
            ['code'=>'as' , 'name' => 'Assamese', 'script' => 'Beng', 'native' => 'অসমীয়া', 'regional' => 'as_IN'],
            ['code'=>'bn' , 'name' => 'Bengali', 'script' => 'Beng', 'native' => 'বাংলা', 'regional' => 'bn_BD'],
            ['code'=>'mni', 'name' => 'Manipuri', 'script' => 'Beng', 'native' => 'মৈতৈ', 'regional' => 'mni_IN'],
            ['code'=>'pa' , 'name' => 'Punjabi (Gurmukhi)', 'script' => 'Guru', 'native' => 'ਪੰਜਾਬੀ', 'regional' => 'pa_IN'],
 			['code'=>'gu' , 'name' => 'Gujarati', 'script' => 'Gujr', 'native' => 'ગુજરાતી', 'regional' => 'gu_IN'],
            ['code'=>'or' , 'name' => 'Oriya', 'script' => 'Orya', 'native' => 'ଓଡ଼ିଆ', 'regional' => 'or_IN'],
            ['code'=>'ta' , 'name' => 'Tamil', 'script' => 'Taml', 'native' => 'தமிழ்', 'regional' => 'ta_IN'],
            ['code'=>'te' , 'name' => 'Telugu', 'script' => 'Telu', 'native' => 'తెలుగు', 'regional' => 'te_IN'],
            ['code'=>'kn' , 'name' => 'Kannada', 'script' => 'Knda', 'native' => 'ಕನ್ನಡ', 'regional' => 'kn_IN'],
            ['code'=>'ml' , 'name' => 'Malayalam',              'script' => 'Mlym', 'native' => 'മലയാളം', 'regional' => 'ml_IN'],
            ['code'=>'si' , 'name' => 'Sinhala', 'script' => 'Sinh', 'native' => 'සිංහල', 'regional' => 'si_LK'],
            ['code'=>'th' , 'name' => 'Thai', 'script' => 'Thai', 'native' => 'ไทย', 'regional' => 'th_TH'],
            ['code'=>'lo' , 'name' => 'Lao', 'script' => 'Laoo', 'native' => 'ລາວ', 'regional' => 'lo_LA'],
            ['code'=>'bo' , 'name' => 'Tibetan', 'script' => 'Tibt', 'native' => 'པོད་སྐད་', 'regional' => 'bo_IN'],
            ['code'=>'dz' , 'name' => 'Dzongkha', 'script' => 'Tibt', 'native' => 'རྫོང་ཁ', 'regional' => 'dz_BT'],
            ['code'=>'my' , 'name' => 'Burmese', 'script' => 'Mymr', 'native' => 'မြန်မာဘာသာ', 'regional' => 'my_MM'],
            ['code'=>'ka' , 'name' => 'Georgian', 'script' => 'Geor', 'native' => 'ქართული', 'regional' => 'ka_GE'],
            ['code'=>'byn', 'name' => 'Blin', 'script' => 'Ethi', 'native' => 'ብሊን', 'regional' => 'byn_ER'],
            ['code'=>'tig', 'name' => 'Tigre', 'script' => 'Ethi', 'native' => 'ትግረ', 'regional' => 'tig_ER'],
            ['code'=>'ti' , 'name' => 'Tigrinya', 'script' => 'Ethi', 'native' => 'ትግርኛ', 'regional' => 'ti_ET'],
            ['code'=>'am' , 'name' => 'Amharic', 'script' => 'Ethi', 'native' => 'አማርኛ', 'regional' => 'am_ET'],
            ['code'=>'wal', 'name' => 'Wolaytta', 'script' => 'Ethi', 'native' => 'ወላይታቱ', 'regional' => 'wal_ET'],
            ['code'=>'chr', 'name' => 'Cherokee', 'script' => 'Cher', 'native' => 'ᏣᎳᎩ', 'regional' => ''],
            ['code'=>'iu' , 'name' => 'Inuktitut (Canadian Aboriginal Syllabics)', 'script' => 'Cans', 'native' => 'ᐃᓄᒃᑎᑐᑦ', 'regional' => 'iu_CA'],
            ['code'=>'oj' , 'name' => 'Ojibwa', 'script' => 'Cans', 'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'regional' => ''],
            ['code'=>'cr' , 'name' => 'Cree', 'script' => 'Cans', 'native' => 'ᓀᐦᐃᔭᐍᐏᐣ', 'regional' => ''],
            ['code'=>'km' , 'name' => 'Khmer', 'script' => 'Khmr', 'native' => 'ភាសាខ្មែរ', 'regional' => 'km_KH'],
 			['code' => 'mn-Mong', 'name' => 'Mongolian (Mongolian)',  'script' => 'Mong', 'native' => 'ᠮᠣᠨᠭᠭᠣᠯ ᠬᠡᠯᠡ', 'regional' => 'mn_MN'],
 			['code' => 'shi-Tfng', 'name' => 'Tachelhit (Tifinagh)',   'script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'regional' => ''],
            ['code'=>'tzm', 'name' => 'Central Atlas Tamazight (Tifinagh)','script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'regional' => ''],
            ['code'=>'yue', 'name' => 'Yue', 'script' => 'Hant', 'native' => '廣州話', 'regional' => 'yue_HK'],
            ['code'=>'ja' , 'name' => 'Japanese', 'script' => 'Jpan', 'native' => '日本語', 'regional' => 'ja_JP'],
            ['code'=>'zh' , 'name' => 'Chinese (Simplified)',   'script' => 'Hans', 'native' => '简体中文', 'regional' => 'zh_CN'],
 			['code' => 'zh-Hant', 'name' => 'Chinese (Traditional)',  'script' => 'Hant', 'native' => '繁體中文', 'regional' => 'zh_CN'],
            ['code'=>'ii' , 'name' => 'Sichuan Yi',             'script' => 'Yiii', 'native' => 'ꆈꌠꉙ', 'regional' => ''],
            ['code'=>'vai', 'name' => 'Vai (Vai)',              'script' => 'Vaii', 'native' => 'ꕙꔤ', 'regional' => ''],
 			['code' => 'jv-Java', 'name' => 'Javanese (Javanese)',    'script' => 'Java', 'native' => 'ꦧꦱꦗꦮ', 'regional' => ''],
            ['code'=>'ko' , 'name' => 'Korean', 'script' => 'Hang', 'native' => '한국어', 'regional' => 'ko_KR'],

        ];

        foreach($languages as $language){
        	Language::create($language);
        }

        $enableEnglish = Language::where('code', '=', 'en')->first();
        $enableEnglish->active = true;
        $enableEnglish->save();
    }
}
